services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 10

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: proghelper
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    command: ["python", "-m", "bot.main"]
    environment:
      BOT_TOKEN: 7137305536:AAHD2SdGsRhdXa-gzl3anKU1bVTwr-fbegs
      GIGACHAT_AUTH_KEY: MzFkNjAzODItMDUyMi00YmFmLWFkN2EtOTM0ZmNkOTdjZTE0OmQxZWVjY2M2LTFhNzktNDE1OS1iNGQxLTMyNTQ4ODNiMDUyMg==
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/proghelper
      OLLAMA_URL: http://ollama:11434
    depends_on:
      db:
        condition: service_started
      ollama:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  pgdata:
  ollama_data:
